replicaCount: 1

image:
  repository: tek-telemetry
  tag: "v1.0.1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

serviceAccount:
  create: true
  name: ""

podSecurityContext:
  runAsNonRoot: true

containerSecurityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL

livenessProbe:
  enabled: true
  path: /health
  initialDelaySeconds: 5
  periodSeconds: 10

readinessProbe:
  enabled: true
  path: /health
  initialDelaySeconds: 3
  periodSeconds: 5